[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'neoclide/coc.nvim'
on_ft = ['python']
merged=0
rev="release"
hook_source = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''
